MATCH (change:Change)
WHERE change.external_id = 'CHG-8821' OR change.id = 'CHG-8821'
WITH change
ORDER BY CASE WHEN change.dataset = 'vexpertai-design-ontology' THEN 0 ELSE 1 END
LIMIT 1
MATCH path=(change)-[
  :MODIFIES|AFFECTS|INTRODUCES_RISK|EVIDENCES|REFERENCES|
  ROUTE_MAP_CONTROLS_REDISTRIBUTION|PREFIX_LIST_CONTROLS_PREFIX_VISIBILITY|
  REDISTRIBUTION_PRODUCES_BGP_ROUTE|BGP_ROUTE_CARRIES_PREFIX|
  SUPPORTS_LAYER|IMPACTS|BASED_ON|REQUIRES
  *1..6
]-(related)
RETURN path
LIMIT 250;
